[tool.poetry]
name = "brew_control_client"
version = "0.1.0"
description = "Controls our brewery."
authors = ["Michael Cannamela <m.cannamela@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
matplotlib = ">=3.10.7"
python-dateutil = ">=2.8.2"
pytz = ">=2025.2"
requests = ">=2.32.5"
scipy = ">=1.16.3"

[tool.poetry.group.dev.dependencies]
mock = ">=5.2.0"
pytest = ">=9.0.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
